jobs:
- job: ${{ parameters.name }}
  dependsOn:
  - 'build_sut'
  variables:
    - group: LINTLY
    - name: nuget
      value: packages
    - name: python_version
      value: ${{ parameters.python_version }}
    - name: extra_atest_params
      value: ${{ parameters.extra_atest_params  }}
  steps:
  - task: UsePythonVersion@0
    displayName: 'Setup Python'
    inputs:
      versionSpec: $(python_version)
      addToPath: true
      architecture: 'x64'

  - script: |
        pip install -r requirements-dev.txt
    displayName: Install needed components from PyPi

  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: 'build_artifacts'
    displayName: Copying White from pipeline artifacts.

  - script: |
      mkdir src\WhiteLibrary\bin\
      copy $(nuget)\Castle.Core.3.3.0\lib\net45\Castle.Core.dll src\WhiteLibrary\bin\
      copy $(nuget)\TestStack.White.0.13.3\lib\net40\TestStack.White.dll src\WhiteLibrary\bin\
    continueOnError: false
    displayName: Copy binaries to the library package

  - script: |
        python -m xmlrunner discover -s src --output-file unittests_$(python_version).xml
    displayName: Run Python unit tests

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunner: JUnit
      testResultsFiles: unittests_$(python_version).xml

  - script: |
        python setup.py install
    displayName: Install WhiteLibrary

  - script: |
      robot --outputdir output --noncritical unstable --xunit acceptancetests_$(python_version).xml $(extra_atest_params) --loglevel DEBUG:INFO atests
    displayName: Execute Acceptance tests

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunner: JUnit
      testResultsFiles: output/acceptancetests_$(python_version).xml

  - script: |
      mkdir sareports
      flake8 --output sareports/flake8_$(python_version).xml --format=junit-xml
    displayName: 'Running Flake8 Static Analysis'
    condition: and(always(), ne(variables['Build.Reason'],'PullRequest'))
    continueOnError: true

  - script: |
      flake8 --exit-zero | lintly  --format=flake8 --log --post-status --exit-zero
    displayName: 'Running Flake8 Static Analysis For Pull Request'
    condition: and(always(), eq(variables['Build.Reason'],'PullRequest'), eq(variables['python_version'], '3.6'))
    continueOnError: true

  - task: PublishTestResults@2
    condition: and(always(), ne(variables['Build.Reason'],'PullRequest'))
    continueOnError: true
    inputs:
      testRunner: JUnit
      testResultsFiles: sareports/flake8_$(python_version).xml
      testResultsTitle: Static Analysis Results from Flake8
      testRunTitle: flake8-results-$(python_version)
      publishRunAttachments: true
      failTaskOnFailedTests: true

  - script: |
      pylint src --output-format=junit > sareports/pylint_$(python_version).xml
    displayName: 'Running Pylint Static Analysis'
    condition: and(always(), in(variables['python_version'], '3.4', '3.5', '3.6'), ne(variables['Build.Reason'],'PullRequest'))
    continueOnError: true

  - task: PublishTestResults@2
    condition: and(always(), in(variables['python_version'], '3.4', '3.5', '3.6'), ne(variables['Build.Reason'],'PullRequest'))
    continueOnError: true
    inputs:
      testRunner: JUnit
      testResultsFiles: sareports/pylint_$(python_version).xml
      testResultsTitle: Static Analysis Results from Pylint
      testRunTitle: pylint-results-(python_version)
      publishRunAttachments: true
      failTaskOnFailedTests: true

  - task: PublishBuildArtifacts@1
    condition: always()
    displayName: Publish Robot Framework logs and results
    inputs:
      PathtoPublish: output
      ArtifactType: container
      TargetPath: ""
      ArtifactName: Robot Test results

  - task: PublishBuildArtifacts@1
    condition: and(always(), ne(variables['Build.Reason'],'PullRequest'))
    displayName: Archive Static Analysis Reports
    inputs:
      PathToPublish: sareports
      ArtifactType: container
      TargetPath: ""
      ArtifactName: StaticAnalysis
