
steps:
- script: |
      pip install robotframework
      pip install pythonnet
  displayName: Install needed compoments from PyPi

- task: NuGetCommand@2

- task: VSBuild@1

- script: |
    run_tests.cmd --exclude no_ci --xunit xunit.xml
  continueOnError: true
  displayName: Execute Acceptance tests

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: output/xunit.xml


- task: Bash@3
  inputs:
    targetType: inline
    script: echo $BUILD_BUILDNUMBER >> build.info

- task: PublishBuildArtifacts@1
  displayName: Publish Robot Framework logs and results
  inputs:
    PathtoPublish: output
    ArtifactType: container
    TargetPath: ""
    ArtifactName: Robot Test results

- task: PublishBuildArtifacts@1
  displayName: Publish build.info
  inputs:
    PathToPublish: build.info
    ArtifactType: container
    TargetPath: ""
    ArtifactName: WhiteLibrary

- task: PublishBuildArtifacts@1
  displayName: Publish whitelibrary DLL
  inputs:
    PathToPublish: WhiteLibrary/bin/CSWhiteLibrary.dll
    ArtifactType: container
    TargetPath: "bin/"
    ArtifactName: WhiteLibrary

- task: PublishBuildArtifacts@1
  displayName: Publish Whitelibrary.py
  inputs:
    PathToPublish: PythonWhiteLibrary/src/WhiteLibrary.py
    ArtifactType: container
    TargetPath: ""
    ArtifactName: WhiteLibrary

- task: PublishBuildArtifacts@1
  displayName: Publish __init__.py
  inputs:
    PathToPublish: PythonWhiteLibrary/src/__init__.py
    ArtifactType: container
    TargetPath: ""
    ArtifactName: WhiteLibrary

- task: PublishBuildArtifacts@1
  displayName: Publish setup.py
  inputs:
    PathToPublish: PythonWhiteLibrary/setup.py
    ArtifactType: container
    TargetPath: ""
    ArtifactName: WhiteLibrary

- task: PublishBuildArtifacts@1
  displayName: Publish Dependency library DLL
  inputs:
    PathToPublish: WhiteLibrary/bin/Castle.Core.dll
    ArtifactType: container
    TargetPath: "bin/"
    ArtifactName: WhiteLibrary

- task: PublishBuildArtifacts@1
  displayName: Publish Dependency library DLL
  inputs:
    PathToPublish: WhiteLibrary/bin/TestStack.White.dll
    ArtifactType: container
    TargetPath: "bin/"
    ArtifactName: WhiteLibrary

- task: PublishBuildArtifacts@1
  displayName: Publish Dependency library DLL
  inputs:
    PathToPublish: WhiteLibrary/bin/TestStack.White.Reporting.dll
    ArtifactType: container
    TargetPath: "bin/"
    ArtifactName: WhiteLibrary

- task: PublishBuildArtifacts@1
  displayName: Publish Dependency library DLL
  inputs:
    PathToPublish: WhiteLibrary/bin/TestStack.White.ScreenObjects.dll
    ArtifactType: container
    TargetPath: "bin/"
    ArtifactName: WhiteLibrary

