
steps:
- script: |
      pip install robotframework
      pip install pythonnet
  displayName: Install needed compoments from PyPi

- task: NuGetCommand@2

- task: VSBuild@1

- script: |
    run_tests.cmd --exclude no_ci --xunit xunit.xml
  continueOnError: true
  displayName: Execute Acceptance tests

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: output/xunit.xml

- task: PublishBuildArtifacts@1
  displayName: Publish Robot Framework logs and results
  inputs:
    PathtoPublish: output
    ArtifactType: container
    TargetPath: ""
    ArtifactName: Robot Test results
