jobs:
- job: 'build_sut'
  steps:
    - task: NuGetToolInstaller@0
      inputs:
        versionSpec: '4.3.0'

    - script: |
          mkdir UIAutomationTest\packages
          nuget restore UIAutomationTest\packages.config -PackagesDirectory UIAutomationTest\packages
          nuget restore src\WhiteLibrary\packages.config -PackagesDirectory packages
      displayName: Download All NuGet packages

    - task: VSBuild@1
      inputs:
        solution: UIAutomationTest\UIAutomationTest.csproj

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'build_artifacts'
      displayName: 'Publish Build Artifacts'

- template: .jobtemplate.yml
  parameters:
    name: 'white_py27'
    extra_atest_params: --exclude no_ci
    python_version:  2.7

- template: .jobtemplate.yml
  parameters:
    name: 'white_py36'
    extra_atest_params: --exclude no_ci
    python_version:  3.6

- job: 'release'
  dependsOn:
  - 'white_py36'
  - 'white_py27'
  steps:
    - task: UsePythonVersion@0
      displayName: 'Setup Python'
      inputs:
        versionSpec: 3.6
        addToPath: true
        architecture: 'x64'

    - script: |
        pip install -r requirements-dev.txt
      condition: succeeded()
      displayName: 'Install Release Dependencies'

    - task: Bash@3
      inputs:
        targetType: inline
        script: echo $BUILD_BUILDNUMBER >> build.info
      displayName: Generate build.info

    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'build_artifacts'
      displayName: Copying White from pipeline artifacts.

    - script: |
        mkdir src\WhiteLibrary\bin\
        copy packages\Castle.Core.3.3.0\lib\net45\Castle.Core.dll src\WhiteLibrary\bin\
        copy packages\Salabs.TestStack.White.0.13.4\lib\net40\TestStack.White.dll src\WhiteLibrary\bin\
      continueOnError: false
      displayName: Copy binaries to the library package

    - script: |
        python setup.py sdist --formats=zip bdist_wheel --universal
      condition: succeeded()
      displayName: 'Build Python package'

    - task: PublishBuildArtifacts@1
      condition: succeeded()
      displayName: Publish Python packages
      inputs:
        PathToPublish: dist
        ArtifactType: container
        TargetPath: ""
        ArtifactName: WhiteLibrary packages

    - task: TwineAuthenticate@0
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        externalFeeds: 'PyPi'

    - script: |
        twine upload -r PyPi --config-file $(PYPIRC_PATH) dist/*.whl dist/*.zip
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      displayName: 'Upload packages to PyPI'
