jobs:
- template: .jobtemplate.yml
  parameters:
    name: 'white_py27_build'
    extra_atest_params: --exclude no_ci
    python_version:  2.7
    make_release: false

- template: .jobtemplate.yml
  parameters:
    name: 'white_py36_build_and_release'
    extra_atest_params: --exclude no_ci
    python_version:  3.6
    make_release: true

