variables:
  deployment_base: deploy
  deployment_bin: deploy/bin
  nuget_base: PythonWhiteLibrary/src

steps:
- script: |
      pip install robotframework
      pip install pythonnet
  displayName: Install needed compoments from PyPi

- task: NuGetCommand@2
  inputs:
    command: custom
    arguments: install TestStack.White -Version 0.13.3 -OutputDirectory ${nuget_base}


- script: |
    set DEPLOYMENT_BASE=${deployment_base}
    set DEPLOYMENT_BIN=${deployment_bin}
    set NUGET_BASE=${nuget_base}
    dir /s
    deploy_structure.cmd
  continueOnError: false
  displayName: Copy build artifacts to deployment directory

- script: |
    set DEPLOYMENT_BASE=${deployment_base}
    set DEPLOYMENT_BIN=${deployment_bin}
    run_tests.cmd --exclude no_ci --xunit xunit.xml
  continueOnError: true
  displayName: Execute Acceptance tests

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: output/xunit.xml

- task: Bash@3
  inputs:
    targetType: inline
    script: echo $BUILD_BUILDNUMBER >> build.info

- task: PublishBuildArtifacts@1
  displayName: Publish Robot Framework logs and results
  inputs:
    PathtoPublish: output
    ArtifactType: container
    TargetPath: ""
    ArtifactName: Robot Test results

- task: PublishBuildArtifacts@1
  displayName: Publish WhiteLibrary
  inputs:
    PathToPublish: ${deployment_base}
    ArtifactType: container
    TargetPath: ""
    ArtifactName: WhiteLibrary
